# Run a Redis instance and Celery workers.
version: "3"
services:
  redis:
    image: redis:6
    ports:
    - "6379:6379"
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["poetry", "run", "celery", "--app=distribute_challenge.execution_backends.celery", "worker",  "--concurrency=1", "--events"]
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    volumes:
      - .:/app
    depends_on:
      - redis
