name: Tests
on: [push]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.6]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install package and dependencies
        run: python -m poetry install
      - name: Run worker
        run: python -m poetry run celery -A distribute_challenge.execution_backends.celery worker --detach
      - name: Run tests
        run: python -m poetry run pytest --doctest-modules --cov
